name: Jenkins Build

on:
  push:
    branches:
      - feature/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins build
        uses: jenkinsci/github-plugin@1.29.5
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          job: jira-performance-test
          username: admin
          password: ${{ secrets.JENKINS_TOKEN }}