name: Jenkins build
on:
  push:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - name: Run DC App Performance Toolkit
        run: docker run --shm-size=4g -v "$PWD:/dc-app-performance-toolkit" atlassian/dcapt jira.yml
      - name: Zip artifact for deployment
        run: zip -r jira-results.zip . -i /app/results/jira/**/*
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: jira-results.zip
