name: Jenkins Build

on:
  push:
    branches:
      - feature/cicd

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: jenkins
      uses: enflo/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: admin
        token: ${{ secrets.JENKINS_TOKEN }}
        job: jira-performance-test
        parameters: |
          application_hostname=${{ inputs.application_hostname }}
          application_protocol=${{ inputs.application_protocol }}
          application_port=${{ inputs.application_port }}
          admin_login=${{ inputs.admin_login }}
          admin_password=${{ inputs.admin_password }}
          concurrency=${{ inputs.concurrency }}
          test_duration=${{ inputs.test_duration }}
          ramp-up=${{ inputs.ramp-up }}
          total_actions_per_hour=${{ inputs.total_actions_per_hour }}