name: Jenkins build
on:
  push:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: docker://atlassian/dcapt:7.3.0
        with:
          args: >-
            --shm-size=4g
            jira.yml
          folder: /dc-app-performance-toolkit/app