name: Jenkins build
on:
  push:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run test
      uses: docker://atlassian/dcapt:7.3.0
      with:
        options: >-
          --volume=${{ github.workspace }}/dc-app-performance-toolkit:/github/home/dc-app-performance-toolkit
          --shm-size=4g
        args: jira.yml