name: Jenkins build
on:
  push:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: docker://atlassian/dcapt:7.3.0
        with:
          options: >-
            --shm-size=4g
            --volume=${{ github.workspace }}/app:dc-performance-toolkit/app
          args: jira.yml
          fail-on-error: true