name: Jenkins build
on:
  push:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://atlassian/dcapt:7.3.0
      options: >-
        --shm-size=4g
        --volume=./dc-app-performance-toolkit:/dc-app-performance-toolkit
        --entrypoint jira.yml